import ImageContent from "../common/ImageContent";

export const Program = () => {
  return (
    <div className="program">
      <ImageContent
        src="/img/program/img_01.png"
        mobileSrc="/img/program/mobile/img_01.png"
        alt="img_01"
        backgroundColor="#011221"
      />
      <ImageContent
        src="/img/program/img_02.png"
        mobileSrc="/img/program/mobile/img_02.png"
        alt="img_02"
        backgroundColor="#001734"
      />
      <ImageContent
        src="/img/program/img_03.png"
        mobileSrc="/img/program/mobile/img_03.png"
        alt="img_03"
        backgroundColor="#EEF5FF"
      />
      <ImageContent
        src="/img/program/img_04.png"
        mobileSrc="/img/program/mobile/img_04.png"
        alt="img_04"
        backgroundColor="#FFFFFF"
      />
      <ImageContent
        src="/img/program/img_05.png"
        mobileSrc="/img/program/mobile/img_05.png"
        alt="img_05"
        backgroundColor="#EEF5FF"
      />
      <ImageContent
        src="/img/program/img_06.png"
        mobileSrc="/img/program/mobile/img_06.png"
        alt="img_06"
        backgroundColor="#001734"
      />
      <ImageContent
        src="/img/program/img_07.png"
        mobileSrc="/img/program/mobile/img_07.png"
        alt="img_07"
        backgroundColor="#FFFFFF"
      />
      <ImageContent
        src="/img/program/img_08.png"
        mobileSrc="/img/program/mobile/img_08.png"
        alt="img_08"
        backgroundColor="#FFFFFF"
      />
      <ImageContent
        src="/img/program/img_09.png"
        mobileSrc="/img/program/mobile/img_09.png"
        alt="img_09"
        backgroundColor="#001734"
      />
      <ImageContent
        src="/img/program/img_10.png"
        mobileSrc="/img/program/mobile/img_10.png"
        alt="img_10"
        backgroundColor="#EFF6FF"
      />
      <ImageContent
        src="/img/program/img_11.png"
        mobileSrc="/img/program/mobile/img_11.png"
        alt="img_11"
        backgroundColor="#FFFFFF"
      />
      <ImageContent
        src="/img/program/img_12.png"
        mobileSrc="/img/program/mobile/img_12.png"
        alt="img_12"
        backgroundColor="#F8F9FB"
      />
      <ImageContent
        src="/img/program/img_13.png"
        mobileSrc="/img/program/mobile/img_13.png"
        alt="img_13"
        backgroundColor="#FFFFFF"
      />
      <ImageContent
        src="/img/program/img_14.png"
        mobileSrc="/img/program/mobile/img_14.png"
        alt="img_14"
        backgroundColor="#001734"
      />
      <ImageContent
        src="/img/program/img_15.png"
        mobileSrc="/img/program/mobile/img_15.png"
        alt="img_15"
        backgroundColor="#021937"
      />
    </div>
  );
};
